# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.2.1"
remodel = "rojo-rbx/remodel@0.10.0"
stylua = "johnnymorganz/stylua@0.14.1"
wally = "upliftgames/wally@0.3.1"
tarmac = "jeparlefrancais/tarmac@0.7.1"
selene = "kampfkarren/selene@0.20.0"
# rojo = "rojo-rbx/rojo@6.2.0"